<a href="https://colab.research.google.com/github/Eun0416/2026-1-BDA/blob/main/code/06w_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 06 테이블 분석 패키지 pandas

## 6.2 데이터프레임 생성 (21page~)

### 다양한 데이터 프레임 생성 방법

In [1]:
import pandas as pd
import numpy as np

In [2]:
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name = 'courses')
fees = pd.Series([250000, 300000, 200000], name = 'fees')

df = pd.DataFrame([courses, fees])
df

              0        1       2
courses   Spark  PySpark  Hadoop
fees     250000   300000  200000

In [3]:
df.T

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [4]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [5]:
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name = 'courses')
df[courses.name] = courses
df

   courses
0    Spark
1  PySpark
2   Hadoop

In [6]:
fees = pd.Series([250000, 300000, 200000], name = 'fees')
df[fees.name] = fees
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

### 여러 dict의 목록 데이터

In [7]:
import pandas as pd

df = pd.DataFrame([{'국어' : 70, '수학' : 89, '영어' : 90},
                   {'국어' : 80, '영어' : 99},
                   {'수학' : 66, '영어' : 78}])
df

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  99
2   NaN  66.0  78

In [8]:
import pandas as pd

s1 = pd.Series([90, 80, 60, 66])
s2 = pd.Series([45, 74, 83, 99])
s3 = pd.Series([92, 75, 82, 75])
s1

0    90
1    80
2    60
3    66
dtype: int64

In [9]:
df = pd.DataFrame({'국어' : s1, '영어' : s2, '수학' : s3})
df

   국어  영어  수학
0  90  45  92
1  80  74  75
2  60  83  82
3  66  99  75

In [10]:
df.index = ['노', '장', '박', '강']
df

   국어  영어  수학
노  90  45  92
장  80  74  75
박  60  83  82
강  66  99  75

### 데이터 프레임의 결측값 표시 NaN

In [11]:
df = pd.DataFrame({'A' : pd.Series([10, 20, 30], index=[0, 1, 2]),
                   'B' : pd.Series([3, 2, 1], index=[1, 2, 3])})
df

      A    B
0  10.0  NaN
1  20.0  3.0
2  30.0  2.0
3   NaN  1.0

In [12]:
s1 = pd.Series([90, 80, 60], index = ['노', '장', '박'])
s2 = pd.Series([45, 73, 99], index = ['장', '박', '강'])
s3 = pd.Series([92, 75, 82, 75])

In [13]:
df = pd.DataFrame({'국어' : s1, '영어' : s2, '수학' : s3},
                  index = ['노', '장', '박', '강'])
df

     국어    영어  수학
노  90.0   NaN NaN
장  80.0  45.0 NaN
박  60.0  73.0 NaN
강   NaN  99.0 NaN

### df.dtypes
#### 자료형

In [14]:
d = {'col1' : [1, 2], 'col2' : [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [15]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [16]:
df = pd.DataFrame(data = d, dtype=np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

### 여러 날짜 시퀀스를 위한 함수 date_range()

In [17]:
dates = pd.date_range("20250101", periods=6)
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

In [18]:
dates[0]

Timestamp('2025-01-01 00:00:00')

In [19]:
dates = pd.date_range("20250101", end='20250110')
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

### 인자 freq

In [20]:
dates = pd.date_range("20250101", periods=6, freq='3D')
dates

DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16'],
              dtype='datetime64[ns]', freq='3D')

In [21]:
dates = pd.date_range("20250101", periods=6, freq='3H')
dates

/tmp/ipykernel_42504/3819429892.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("20250101", periods=6, freq='3H')

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 03:00:00',
               '2025-01-01 06:00:00', '2025-01-01 09:00:00',
               '2025-01-01 12:00:00', '2025-01-01 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [22]:
dates = pd.date_range("20250101", periods=6, freq='W')
dates

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

In [23]:
dates = pd.date_range("20260101", periods=6, freq='W-SUN')
dates

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

In [24]:
dates = pd.date_range("20260101", periods=6, freq='W-TUE')
dates

DatetimeIndex(['2026-01-06', '2026-01-13', '2026-01-20', '2026-01-27',
               '2026-02-03', '2026-02-10'],
              dtype='datetime64[ns]', freq='W-TUE')

In [25]:
dates = pd.date_range("20260101", periods=6, freq='W-FRI')
dates

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

In [26]:
dates = pd.date_range("20250101", periods=6, freq='M') # ME로 지정할 것
dates

/tmp/ipykernel_42504/19627744.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq='M') # ME로 지정할 것

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [27]:
dates = pd.date_range("20250101", periods=6, freq='MS')
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

### 날짜를 포함한 데이터프레임

In [28]:
dates = pd.date_range("20250302", periods = 6)
dates

DatetimeIndex(['2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05',
               '2025-03-06', '2025-03-07'],
              dtype='datetime64[ns]', freq='D')

In [29]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-03-02  1.231312  0.028516  0.291893 -1.025346
2025-03-03 -2.255707  1.150231  0.131864 -0.434296
2025-03-04  0.111366 -0.625736  1.677071 -1.077624
2025-03-05  0.391862 -1.130832  0.335684  0.101173
2025-03-06 -0.004208 -0.998025 -0.277170 -0.928659
2025-03-07 -0.450428  0.627125 -1.115376  0.498833

### 다양한 자료형으로 구성된 데이터프레임

In [30]:
df2 = pd.DataFrame({
    "A" : 1.0,
    "B" : pd.Timestamp("20260302"),
    "C" : pd.Series(np.arange(1, 3, .5)),
    "D" : np.array([3] * 4, dtype="int32"),
    "E" : pd.Categorical(["test", "train", "test", "train"]),
    "F" : "foo"
})
df2

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

In [31]:
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

## 6.3 DataFrame의 다양한 참조

### 데이터 프레임 열 참조

In [32]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [33]:
pf['과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [34]:
pf.과제 # 시리즈

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [35]:
pf[ ['과제'] ] # 데이터프레임

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [36]:
pf[ ['과제', '기말'] ]

     과제  기말
윤일형   8  35
강수희  10  27
홍소희  10  17
유한빈   9  22
신수빈   8  34

In [37]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [38]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [39]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [40]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [41]:
pf[['기말', '출석', '중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [42]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

### 조건에 맞는 행 참조

In [43]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [44]:
pf['중간'] > 20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [45]:
pf[pf['중간'] > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [46]:
pf[pf['출석'] >= 19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [47]:
pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

### df.loc[]

In [48]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [49]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [50]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [51]:
pf.loc[['홍소희', '윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [52]:
pf.loc['윤일형' : '유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [53]:
pf.loc[pf.중간 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [54]:
pf.loc[(pf.중간 > 10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [55]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [56]:
pf.loc[pf.index[0]] # 첫 번째 행 검색

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [57]:
pf.loc[[pf.index[0]]] # 첫 번째 행 검색

     중간  기말  과제  출석
윤일형  25  35   8  18

In [58]:
pf.loc[pf.index[1:4]] # 슬라이싱 행 검색

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [59]:
pf.loc[pf.index[1:4]][['기말', '과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

### 열 참조
#### pf.loc[:, '열명']으로 '열명' 전체를 시리즈로 반환

In [60]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [61]:
pf.loc[:, '과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [62]:
pf.loc[:, '중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [63]:
pf.loc[:, ['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

#### loc[:, columns[i]]로 열 참조

In [64]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [65]:
pf.loc[:, pf.columns[0]] # 첫 번째 열 조회

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [66]:
pf.loc[:, [pf.columns[0]] ] # 첫 번째 열 조회 데이터 프레임 반환

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

In [67]:
pf.loc[:, pf.columns[1:]] # 슬라이싱 열 검색

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [68]:
pf.loc[:, pf.columns[1:3]]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [69]:
pf.loc[:, pf.columns[1:]][['기말', '과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

### 행과 열 참조
#### df.loc['행명', '열명']으로 행과 열에 맞는 한 원소를 참조

In [70]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [71]:
pf.loc['윤일형', '출석']

np.int64(18)

In [72]:
pf.loc['윤일형': '유한빈', '기말']

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

In [73]:
pf.loc['윤일형':'유한빈', '기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

In [74]:
pf.loc[pf.index[0], pf.columns[1]]

np.int64(35)

In [75]:
pf.loc[pf.index[0:3], pf.columns[2]]

윤일형     8
강수희    10
홍소희    10
Name: 과제, dtype: int64

In [76]:
pf.loc[pf.index[0:3], pf.columns[2:]]

     과제  출석
윤일형   8  18
강수희  10  20
홍소희  10  19

### df.iloc 참조

#### df.iloc[정수]로 정수 index의 행을 참조

In [77]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [78]:
pf.iloc[1]

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

In [79]:
pf.iloc[[1]]

     중간  기말  과제  출석
강수희  18  27  10  20

In [80]:
pf.iloc[[1, 3]]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [81]:
pf.iloc[[1, 3]]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [82]:
pf.iloc[2:]

     중간  기말  과제  출석
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

#### df.iloc[:, 정수]로 정수 columns의 열을 참조

In [83]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [84]:
pf.iloc[:, 2]

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [85]:
pf.iloc[:, [2]]

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [86]:
pf.iloc[:, 1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

 #### df.iloc[행번호, 열번호]

In [87]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [88]:
pf.iloc[1, 1]

np.int64(27)

In [89]:
pf.iloc[1:3, 1:]

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

In [90]:
pf.iloc[:, 1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [91]:
pf.iloc[[1, 3, 4], 1:]

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

In [92]:
pf.iloc[[1, 3, 4], [0, 1]]

     중간  기말
강수희  18  27
유한빈  12  22
신수빈  22  34

### at['행명', '열명'] 참조
- 레이블 기반으로 참조하는 방식으로 단 하나의 원소를 참조
- 하나의 값을 참조하므로 속도가 빠른 장점

In [93]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [94]:
pf.at['윤일형', '과제']

np.int64(8)

In [95]:
pf.at['유한빈', '기말']

np.int64(22)

In [96]:
pf.at[pf.index[1], '출석']

np.int64(20)

In [97]:
pf.at[pf.index[3], pf.columns[2]]

np.int64(9)

### iat[i, j] 참조
- 정수 첨자 기반의 참조 방식으로 단 하나의 원소를 참조

In [98]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [99]:
pf.iat[1, 2]

np.int64(10)

In [100]:
pf.iat[2, 3]

np.int64(19)

# 07 데이터 프레임 정보와 검색 활용/

## 7.1 데이터프레임 정보와 조건 검색

### 데이터 프레임 준비

In [101]:
import pandas as pd

df = pd.read_csv('2016년졸음운전.csv', encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [102]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [104]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [105]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

### 데이터프레임 합 계산

In [106]:
df.sum() # 모든 열의 합

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [107]:
df.sum(axis=0) # 축 axis=0에 따라 위에서 아래로 수직으로 합

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [108]:
df.sum(axis=1) # 왼쪽에서 오른쪽으로 수평으로 모든 행의 합

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [109]:
df.cumsum(axis=0) # 위에서 아래로 수직으로 누적 합

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [110]:
df.cumsum(axis=1) # 왼쪽에서 오른쪽으로 수평으로 누적 합

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

### 데이터프레임 평균 계산

In [111]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [112]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [113]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [114]:
df.mean(axis=None)

np.float64(206.38888888888889)

### 데이터프레임 최대 최소 계산

In [115]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [116]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [117]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [118]:
df.max(axis=None)

522

In [119]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [120]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [121]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [122]:
df.min(axis=None)

4

### 데이터프레임 조회

In [123]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [124]:
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [125]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [126]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

#### 불리안 인덱싱

In [127]:
df2 > 10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [128]:
df[df2 > 10]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    NaN    387
2016년2월     174    NaN    328
2016년3월     217    NaN    435
2016년4월     216    NaN    419
2016년5월     239   13.0    522
2016년6월     200   12.0    362
2016년7월     227    NaN    460
2016년8월     230    NaN    490
2016년9월     187   13.0    347
2016년10월    183    NaN    367
2016년11월    200    NaN    418
2016년12월    168    NaN    364

In [129]:
df2 [ [True]*6 + [False]*7 ]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

### 조건과 isin()

In [130]:
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [131]:
df2[df2['재해자수'] > 400]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [132]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [133]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

### isin(), str.contains()

In [134]:
df['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [135]:
df[ df['사망(명)'].isin([7, 10]) ]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [136]:
df[ (df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350) ]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [137]:
df[ df.index.str.contains('3') ]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

### 논리 첨자로 값 대입

In [138]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [139]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

### 함수 df.query(조건)
- 조건을 만족하는 행 표시

In [140]:
df = pd.DataFrame({'A': range(1, 6),
                   'B': range(6, -3, -2),
                   'C': range(10, 5, -1),
                   'D clmns': range(3, -2, -1),
                   'E': ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [141]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [142]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [143]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [144]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [145]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [146]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

##### 열명 중간에 빈 문자열이 있는 경우
- 반드시 열 명을 백쿼트(back quote, Tab키 위의 키) `D clmns`를 사용
- "D clmns"는 오류가 발생하지 않으나 원하는 결과 안나옴

In [147]:
df.query('A == `D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [148]:
df.query('A == "A clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [149]:
df[df.A == df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [150]:
df.query('A > 3 | B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [151]:
df.query('A > 2 & C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [152]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

#### df.query() 내부의 질의 문자열 내부에서 변수 사용
- @변수명을 사용
- f 문자열로 사용이 가능

In [153]:
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [154]:
num = 3
df.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [155]:
s = "E.str.contains('py')"
df.query(s) # '부분문자열'이 포함된 행의 데이터프레임

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [156]:
s = 'E.str.startswith("g")'
df.query(s) # '시작문자열'로 시작되는 행을 반환

   A  B  C  D clmns   E
3  4  0  7        0  go

In [157]:
s = "E.str.endswith('on')"
df.query(s) # '끝나는문자열'로 종료되는 행의 데이터프레임을 반환

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

# 종료